### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by damien022** [andr3wmac/Torque6Editor#1]
When compiling the latest version, I get some errors on TorqueScriptLexer.cpp
'WordAt' is not a memeber of 'WordList'
Also the .Lenght() function does not seem to exists, I replaced it with .len
Sorry I have no experience with WXWidget so I might have messed up there

**Comment by ericliusunniy** [comment]
he had used the beta.version

**Comment by andr3wmac** [comment]
Hey, my apologies somehow I didn't even notice this issue get posted a month ago.

I didn't update the README yet but I've actually been running off the latest wxWidgets straight from their repo. The whole wxWidgets thing is turning out to be a bit of a barrier of entry for this project so I think I'm going to drop the latest working version into the source to make it easier to compile out of the box.

Let me know if you're still having an issue compiling.

**Comment by ericliusunniy** [comment]
if you want to use the wxWidgets 3.0.2,  you can  replace the function with follow codes:

bool LexerTorqueScript::TSWordlistContainsKey(WordList &list, int length, LexAccessor &styler, int i)
{
    //Note:Use the wxWidgets 3.0.2
    for (int jj = 0; jj < list.len; jj++)
        if (strlen(list.words[jj]) == length)
            if (styler.Match(i, list.words[jj]))
                return true;
        return false;
}

**Comment by andr3wmac** [comment]
I've added wxWidgets directly to the repo and updated the build scripts to point at that. That cuts out a few steps. I've also added setup.h in the right spots so no one has to try to figure that out if it fails to get copied properly.
